// 사용자 제공 업무 이력을 바탕으로 정리. 측정되지 않은 수치나 성과는 추가하지 않습니다.
export const additionalSkills = [
  { title: "AWS & Cloud", items: ["Aurora MySQL Serverless v2, EC2, S3", "VPC, Security Group, Writer/Reader Endpoint", "Secrets Manager, CloudWatch, AWS Budgets", "ACU 용량·비용 검토, SNS 휴대폰 OTP 인증"] },
  { title: "DevOps & Operations", items: ["GitLab → Jenkins → Maven → Spring Boot 배포", "dev/prod 환경 분리, Shell / Cron 자동화", "Apache VirtualHost / Reverse Proxy, 서비스별 포트·LB", "Sectigo SSL, Let's Encrypt / Certbot, DNS CNAME"] },
  { title: "Blockchain & IoT", items: ["Hyperledger Besu(QBFT), PTH 리워드", "UUID ↔ tx_hash 매핑, Callback, 중복 지급 방지", "실패 트랜잭션 재처리, Main Network ↔ ERC-20 Bridge 연계", "키오스크 API, S3 / PowerShell 영상 자동배포"] },
];

export const additionalProjects = [
  {
    id: "farms-mall",
    title: "팜스몰 포인트 상품몰 및 주문·배송·CS 관리 시스템",
    subtitle: "회사 프로젝트 · 플라스틱히어로코리아 · 단독 개발",
    impact: [
      "기존 GNUBOARD 회원·포인트 시스템과 연계한 상품몰 관리 시스템 단독 개발",
      "상품 관리부터 포인트 구매, 배송, 취소·반품·교환까지 업무 흐름 구현",
    ],
    stack: ["PHP", "GNUBOARD", "MySQL", "JavaScript", "HTML/CSS", "Cron"],
    responsibilities: [
      "상품 정보·판매 가격·이미지·판매 여부·노출 순서 관리 화면 및 백엔드 개발",
      "서버에서 상품 가격·잔액을 검증하고 포인트 차감·거래 내역·주문 생성을 하나의 DB 트랜잭션으로 처리",
      "주문번호 기반 중복 요청 검사와 행 잠금 적용, 구매 당시 상품·가격·배송지 보존 및 복수 배송지 관리",
      "취소·반품·교환의 접수·출고보류·회수·입고·검수·최종 처리 단계 구현",
      "검수 후 승인 수량·반품 배송비를 반영한 부분 환불 및 환불 여부 확인·행 잠금 기반 중복 환불 방지",
      "CJ대한통운 배송 조회와 Cron 기반 상태 갱신, 실패 시 마지막 정상 상태 유지 및 재시도 구현",
      "CS·자동 상태변경 이력 기록, DB 마이그레이션 SQL 및 앱 연동 명세 작성",
    ],
    architecture: [
      "관리자 화면 → PHP 백엔드 → MySQL 상품·회원·포인트·주문·클레임·배송 데이터",
      "구매 요청 → 가격·잔액·중복 검증 → 포인트 차감·주문·거래 내역 일괄 반영",
      "취소·반품 요청 → 미출고 확인 또는 회수·입고·검수 → 최종 확정 시 포인트 환불",
      "Cron → CJ 배송 조회 → 최초배송·반품회수·교환재배송 상태 및 처리 이력 갱신",
    ],
    results: [
      "상품·주문·배송·CS 처리를 연결하여 주문별 진행 상황을 확인할 수 있는 관리 기능 구축",
      "주문·포인트 변경의 트랜잭션 처리와 환불 단계 구분으로 데이터 정합성 관리",
      "앱 연동을 위한 DB 구조·구매 및 환불 규칙·상태 표시 기준 문서화",
    ],
    links: { repo: "", doc: "" },
  },
  {
    id: "aurora",
    title: "AWS Aurora Serverless v2 기반 중앙 DB 구축",
    subtitle: "DB 인프라 · 접근 제어 · 모니터링·비용 관리",
    impact: ["외부 서비스와 연동하는 Aurora MySQL Serverless v2 중앙 DB 환경 구축"],
    stack: ["Aurora MySQL", "Serverless v2", "VPC", "Secrets Manager", "CloudWatch", "AWS Budgets"],
    responsibilities: ["Writer / Reader Endpoint를 구분하고 서비스별 DB 연결 구성", "VPC·Security Group·Public Access 설정과 접속 허용 범위 관리", "Secrets Manager를 통한 DB Credential 관리", "CloudWatch로 DB 성능·리소스 확인, ACU 용량 및 비용 검토와 예산 알림 구성"],
    architecture: ["Next.js / Node.js 서비스 → 접근 제어 → Aurora MySQL", "쓰기·읽기 연결 목적에 따른 Endpoint 및 DB 계정 권한 관리"],
    results: ["DB 연결·접근 권한·리소스·비용을 함께 관리하는 운영 환경 구성"],
    links: { repo: "", doc: "" },
  },
  {
    id: "kiosk-media",
    title: "키오스크 영상 자동배포 시스템",
    subtitle: "S3 → API → PowerShell → Windows 키오스크",
    impact: ["키오스크 영상 변경 감지와 파일 배포 과정을 자동화", "다운로드 실패 시 기존 영상을 유지하고 재시도하는 흐름 구성"],
    stack: ["Amazon S3", "Presigned URL", "REST API", "PowerShell", "Windows"],
    responsibilities: ["manifest_version 비교를 통한 변경 감지 및 변경 파일만 다운로드", "Presigned URL 기반 영상 다운로드 연동", "실패 시 기존 영상 유지 및 자동 재시도 처리", "다수 키오스크의 동시 요청을 분산하는 처리 구성"],
    architecture: ["S3 영상 → 배포 API(manifest / Presigned URL) → PowerShell → 로컬 영상", "버전 비교 → 변경 파일 다운로드 → 영상 갱신 / 실패 시 기존 영상 유지·재시도"],
    results: ["현장 기기의 영상 업데이트를 원격 배포 흐름으로 관리", "배포 실패 상황에서도 기존 콘텐츠를 유지하도록 처리"],
    links: { repo: "", doc: "" },
  },
  {
    id: "kiosk-api",
    title: "키오스크 / IoT 수거 API 플랫폼",
    subtitle: "수거 한도 · 회원/비회원 보상 · 통계 API",
    impact: ["실제 키오스크와 서버 간 수거·회원·보상 API 개발 및 운영"],
    stack: ["Java", "Spring Boot", "PHP", "MySQL 8", "REST API", "AWS SNS"],
    responsibilities: ["기기별·사용자별 PET 수거 한도 처리", "회원·비회원 보상 프로세스 및 포인트 데이터 연계", "SNS 기반 휴대폰 OTP 인증 연동", "수거·회원·포인트 데이터의 일/주/월/연 통계 및 Dashboard API 구성", "데이터 마이그레이션 및 정합성 검증"],
    architecture: ["키오스크 → 수거 API → 한도·회원 확인 → 수거 데이터 / 보상 처리", "수거·회원·포인트 데이터 → 집계 API → 운영 Dashboard"],
    results: ["현장 수거 정책과 보상 흐름을 서버 API에서 관리", "운영 현황 조회와 데이터 정합성 확인을 위한 기능 제공"],
    links: { repo: "", doc: "" },
  },
  {
    id: "mobile",
    title: "React Native Android 앱 유지보수 및 기능 설계",
    subtitle: "Android 빌드·배포 · 상품몰·주문·구매내역 설계",
    impact: ["운영 앱의 유지보수와 Android APK 빌드·배포 수행"],
    stack: ["React Native", "Android", "REST API", "PHP GNUBOARD", "Spring Boot"],
    responsibilities: ["Release / Debug APK 빌드 및 배포", "앱 상품몰·주문·구매내역 기능과 API 흐름 설계", "PHP GNUBOARD 레거시와 Spring Boot 서비스 병행 운영"],
    architecture: ["React Native 앱 → 서비스 API → PHP / Spring Boot → MySQL"],
    results: ["앱과 백엔드를 함께 유지보수하며 상품·주문 기능의 연동 구조 설계"],
    links: { repo: "", doc: "" },
  },
  {
    id: "web-infra",
    title: "SSL·도메인 및 Linux 웹 서버 운영",
    subtitle: "Ubuntu · Apache · 인증서 갱신 · 접근 제어",
    impact: ["서비스별 웹 서버 연결, TLS 인증서, 도메인 설정 운영"],
    stack: ["Ubuntu 20.04", "Apache", "UFW", "Sectigo", "Certbot", "DNS"],
    responsibilities: ["Apache VirtualHost / Reverse Proxy 및 서비스별 포트·LB 환경 관리", "UFW·IP Whitelist·MySQL 계정 기반 접근 제어", "Sectigo SSL 발급·갱신·교체 및 Let's Encrypt / Certbot 인증서 관리", "DNS CNAME 인증, 도메인 이전·연결 및 서버 로그·디스크·프로세스 장애 대응"],
    architecture: ["도메인 / DNS → LB·Apache → 서비스별 포트 → 애플리케이션", "인증서·방화벽·DB 접근 권한을 서비스 구성과 함께 관리"],
    results: ["도메인부터 애플리케이션까지 연결 구간을 관리하고 운영 오류 대응"],
    links: { repo: "", doc: "" },
  },
];

export const incidents = [
  { title: "MySQL Lock Wait Timeout", symptom: "로그 정리 작업 중 잠금 대기 시간 초과", response: "잠금 경합과 로그 정리 작업의 영향을 확인하고 로그 정리 전략 변경" },
  { title: "디스크 tmp errno 28", symptom: "임시 파일 생성에 필요한 디스크 공간 부족", response: "임시 파일·로그와 디스크 사용 현황을 확인하고 정리 대상 및 용량 관리 점검" },
  { title: "MySQL only_full_group_by", symptom: "집계 쿼리의 GROUP BY 조건 오류", response: "조회 컬럼과 집계 기준을 검토하고 그룹 기준에 맞게 SQL 수정" },
  { title: "DB 접속·권한 및 Endpoint", symptom: "Public Key Retrieval / Host not allowed / Aurora Reader Endpoint 문제", response: "클라이언트 인증 설정, 접속 호스트·계정 권한, Security Group 및 읽기·쓰기 Endpoint 구분 점검" },
  { title: "SSL Certificate Invalid", symptom: "서비스 인증서 검증 오류", response: "인증서 유효기간·도메인·인증서 체인과 VirtualHost 연결 설정 점검 및 인증서 교체 대응" },
  { title: "Jenkins 배포 장애", symptom: "자동 빌드 또는 배포 단계의 실패", response: "빌드·배포 로그와 환경별 설정, 대상 프로세스·포트를 확인해 실패 구간 추적" },
  { title: "키오스크 manifest 동기화 실패", symptom: "배포 버전과 로컬 영상 동기화 실패", response: "manifest 버전과 다운로드 결과 확인, 기존 영상 유지 및 자동 재시도 처리" },
];
